use_default_settings: true

server:
  secret_key: "ultrasecretkey" # Is overwritten by ${SEARXNG_SECRET}
  image_proxy: true

search:
  formats:
    - html
    - json
    - csv
    - rss

limiter:
  enabled: false
